[package]
name = "datadigger"
version = "0.1.0"
edition = "2021"
author = "Krooxk"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
html2text = "0.5.0"
colored = "2.0.0"
regex = "1.7.2"
